const products = [
  {
    id: "grocery-basket",
    name: "Daily Grocery Basket",
    vendor: "Everest Grocery",
    category: "Groceries",
    price: 1850,
    inventory: 24,
    description: "Rice, lentils, oil, eggs, and daily kitchen essentials.",
    imageClass: "groceries",
  },
  {
    id: "wellness-essentials",
    name: "Wellness Essentials",
    vendor: "New Road Pharmacy",
    category: "Pharmacy",
    price: 920,
    inventory: 18,
    description: "Masks, sanitizer, first-aid supplies, and wellness basics.",
    imageClass: "pharmacy",
  },
  {
    id: "phone-accessories",
    name: "Phone Accessories",
    vendor: "City Mobile Hub",
    category: "Electronics",
    price: 1250,
    inventory: 31,
    description: "Chargers, cables, phone cases, earbuds, and repair items.",
    imageClass: "electronics",
  },
  {
    id: "fresh-produce",
    name: "Fresh Produce Pack",
    vendor: "Ason Fresh Mart",
    category: "Groceries",
    price: 740,
    inventory: 16,
    description: "Seasonal vegetables and fruits packed for daily cooking.",
    imageClass: "produce",
  },
  {
    id: "bakery-box",
    name: "Breakfast Bakery Box",
    vendor: "Boudha Bakery",
    category: "Bakery",
    price: 680,
    inventory: 12,
    description: "Fresh bread, buns, croissants, and sweet breakfast bites.",
    imageClass: "bakery",
  },
  {
    id: "cleaning-kit",
    name: "Home Cleaning Kit",
    vendor: "Mahalaxmi Supplies",
    category: "Home",
    price: 1110,
    inventory: 20,
    description: "Detergent, dishwash, floor cleaner, scrubbers, and wipes.",
    imageClass: "cleaning",
  },
];

function formatCurrency(amount) {
  return `Rs. ${amount.toLocaleString("en-NP")}`;
}
